- kubernetes-evil.el
This suppresses byte-compile warnings
> Load kubernetes.el for using its features

- kubernetes-commands.el
- kubernetes-configmaps.el
- kubernetes-labels.el
- kubernetes-overview.el
- kubernetes-pods.el
- kubernetes-secrets.el
- kubernetes-state.el
- kubernetes-vars.el
- test/kubernetes-deployments-test.el
- test/kubernetes-overview-test.el
- test/resources/get-deployments-response.json
- test/resources/get-pods-response.json
> Implement aggregated overview

- kubernetes-ast.el
- kubernetes-configmaps.el
- kubernetes-deployments.el
- kubernetes-jobs.el
- kubernetes-labels.el
- kubernetes-loading-container.el
- kubernetes-overview.el
- kubernetes-pod-line.el
- kubernetes-pods.el
- kubernetes-secrets.el
- kubernetes-services.el
- kubernetes-state.el
- test/kubernetes-ast-test.el
- test/kubernetes-configmaps-test.el
- test/kubernetes-deployments-test.el
- test/kubernetes-jobs-test.el
- test/kubernetes-labels-test.el
- test/kubernetes-overview-test.el
- test/kubernetes-pods-test.el
- test/kubernetes-secrets-test.el
- test/kubernetes-services-test.el
Extends the rendering AST to allow custom components to be added.
> Custom components

- kubernetes-contexts.el
- test/kubernetes-contexts-test.el
- test/resources/config-view-response-no-namespace.json
Fall back to default namespace if none is configured.
Resolves
#43
> Fall back to default namespace

- lisp/kubernetes-client.el
- lisp/kubernetes-config.el
- lisp/kubernetes-evil.el
- lisp/kubernetes-mode.el
- lisp/kubernetes-overview.el
- lisp/kubernetes.el
- lisp/test/kubernetes-client-test.el
- lisp/test/kubernetes-config-test.el
- lisp/test/kubernetes-mode-test.el
> Config management

- go/Gopkg.lock
- go/client.go
- go/deployments.go
- go/deployments_test.go
- go/k8s_client.go
- go/main.go
- go/pods.go
- go/pods_test.go
Returns 100% of the data currently. Still needs to define required fields. Can be merged.
Depends on #55 
Resolves #51
> Add support for Listing Deployments

- .travis.yml
- Cask
- kubernetes-ast.el
- test/kubernetes-ast-test.el
Fixing the build issues in Travis CI. The tests are failing. I have not fixed that.
> Fixing the Build issues in Travis CI

- kubernetes-popups.el
https://github.com/chrisbarrett/kubernetes-el/issues/98
No test cases added since there are no other cases for the popups I could see.
> Add container option to exec popup

- kubernetes-overview.el
Kubernetes pods can match a deployment by any label. The current code assumes that there's only 1 label, and the label is always called "name". That's not actually true, resulting in all (or no) pods being listed when unfolding any deployment.
This commit applies all `matchLabels` in a deployment to all pods, getting a more accurate list of which pods belong to which deployment.
> Match all selector labels instead of only "name"

- kubernetes-ingress.el
The maintainer asked that the ingress portion be separated from #114
> DRY formatting for ingress too

- Readme.md
> Added a note about disabling automatic refresh

- Makefile
- kubernetes-commands.el
- kubernetes-utils.el
- test/test-helper.el
- Send compile output to stdout also.
- Do not consider warnings as errors for the time being.
> Fixed bugs introduced in #169

- kubernetes-el-tramp.el
- kubernetes.el
Fix for the issue mentioned by @tarsius in https://github.com/kubernetes-el/kubernetes-el/pull/167#issuecomment-870582794
Thank you @tarsius!
> Fix filename conflict with kubernetes-tramp

- kubernetes-el-tramp.el
- kubernetes-popups.el
> Convert popup for file actions to transient

- kubernetes-evil.el
- kubernetes-modes.el
- kubernetes-popups.el
> Used correct refactored function names

- kubernetes-commands.el
> Used generalized state getter for namespaces

- kubernetes-ingress.el
- test/kubernetes-ingress-test.el
- test/resources/get-ingress-response.json
Hosts errored due to `--mapcat` producing a list and not a string. Also Address part was not truncated.
> Ingress: Fix line rendering

- .github/workflows/ci.yaml
> Migrate to v2 of Codecov upload Action

- CHANGELOG.org
- kubernetes-commands.el
- kubernetes-contexts.el
- kubernetes-modes.el
- kubernetes-popups.el
- tests/test-context.el
> Enable renaming of contexts

- CHANGELOG.org
- kubernetes-commands.el
- kubernetes-modes.el
> Terminate kubectl processes on exit

- kubernetes-core.el
- tests/test-core.el
> Core: Add function for parsing CLI-style arg-value strings

- kubernetes-el-tramp.el
- tests/test-tramp.el
> fix(tramp): Used container name from transient arg (#205)

- docs/CHANGELOG.md
- kubernetes-logs.el
- test/kubernetes-contexts-test.el
> New flag `--timestamps` support added for logs command

- docs/CHANGELOG.md
- kubernetes-popups.el
> Fix missing `require` of `kubernetes-el-tramp`

- kubernetes-ast.el
> Add dash package dependency

- .github/workflows/ci.yaml
Also add release-snapshot version to stable pipeline
> ci: Add separate pipeline for snapshot version

- kubernetes-logs.el
- test/kubernetes-logs-test.el
- test/kubernetes-utils-test.el
Improve logs handling by implementing a better buffer naming
convention that includes namespace, resource type, and container
information. Add the ability to refresh log buffers and a command to
list and switch between open log buffers. Fix navigation in log
buffers by removing unnecessary buffer qualification.
Fixes #93
> feat(logs): enhance logs management with buffer naming and refresh

- kubernetes-exec.el
- test/kubernetes-exec-test.el
Standardize Kubernetes exec buffer naming convention between term and vterm
modes and enhance the buffer selection functionality to make it more compatible
with Emacs features like embark.
Also add more tests for exec functionality.
> refactor: standardize buffer naming and improve buffer selection

- kubernetes-logs.el
- test/kubernetes-logs-test.el
Add a new function to list and switch between Kubernetes log buffers, making
it easier to navigate between multiple log views. The implementation includes
proper buffer metadata for compatibility with Embark and simplifies the
interface by directly using buffer names for selection.
> feat(logs): add buffer switching functionality for Kubernetes logs

- test/kubernetes-pods-test.el
Adds comprehensive unit tests for several pod-related functions including:
- kubernetes-pods--read-name
- kubernetes-pods-delete-marked
- kubernetes-display-pod
The tests cover various scenarios including state handling, pod lookup,
error conditions, and proper API interaction.
> test: add unit tests for kubernetes-pods functions

- kubernetes-describe.el
- kubernetes-logs.el
- kubernetes-utils.el
- test/kubernetes-logs-test.el
- test/kubernetes-utils-test.el
Add improved resource selection mechanism for Kubernetes logs, with the following enhancements:
- Store manually selected resources for later use
- Provide clear feedback about currently selected resource in UI
- Add dedicated resource selection command in the transient menu operations
- Make log actions context-aware with when no resource is selected
> feat(logs): enhance resource selection for kubernetes logs

- kubernetes-exec.el
- kubernetes-utils.el
- test/kubernetes-exec-test.el
- test/kubernetes-utils-test.el
Add manual resource selection for exec with persistent selection
between commands. Enhances UX with clear resource feedback in the
transient menu and automatic container selection based on selected
resource. Includes comprehensive test coverage.
> feat(exec): improve resource selection for exec operations

- kubernetes-logs.el
- kubernetes-utils.el
- test/kubernetes-logs-test.el
- test/kubernetes-utils-test.el
Move resource selection functionality from kubernetes-logs to
kubernetes-utils for reusability. This allows shared code between logs
and other operations that need resource selection.
The refactoring includes:
- Moving selected resource variable and related functions to kubernetes-utils
- Renaming functions to use more general names (not logs-specific)
- Updating function parameters to work with different resource types
> refactor(logs): move resource selection functionality to utils

- kubernetes-exec.el
- test/kubernetes-exec-test.el
This commit refactors the exec functionality to use common utilities
from kubernetes-utils instead of having duplicated code. All pod
management functions like resource selection, container discovery, and
buffer naming are now moved to kubernetes-utils to enable reuse across
the codebase. Removing kubernetes-exec specific shared
kubernetes-utils-- name generation to kubernetes-utils resource type
handling functions new shared component architecture
> refactor(exec): migrate pod exec functionality to kubernetes-utils module

- test/kubernetes-exec-test.el
Add test cases for kubernetes-exec-select-resource,
kubernetes-exec-reset-and-launch, kubernetes-exec-switch-buffers,
transient action descriptions, and transient command execution. These
tests ensure proper functionality when selecting resources, handling
> test: add comprehensive unit tests for kubernetes-exec features
