kubernetes-kubectl.el
kubernetes-popups.el
kubernetes-state.el
kubernetes-vars.el
test/kubernetes-kubectl-test.el
test/kubernetes-state-test.el
test/test-helper.el

Adds a number of useful settings to the config popup, and keeps magit's global variables in sync with the application state.
Resolves #4.

Sync the kubernetes-config-popup state with the state manager

---

kubernetes-evil.el
kubernetes-overview.el
kubernetes-state.el
kubernetes-vars.el
test/kubernetes-overview-test.el
test/kubernetes-state-test.el

- Allows users to choose which resources are displayed in the overview. 
- Shows only deployments by default 
- Adds a key binding to switch between the default set of resources (`v` by default)

Make overview customisable

---

kubernetes-ast.el

Improves rendering performance by using a loop instead of deeply nested recursion. NB the Elisp interpreter does not perform TCO.

Rewrite interpreter using a loop

---

kubernetes-commands.el
kubernetes-popups.el
kubernetes-utils.el

This adds a `=c` option to the `kubernetes-logs-popup` which can be used to select the container to read logs from.
This implementation doesn't make use of the `kubernetes-state` (yet) to display the correct containers, but it is an improvement over the current situation where all you can get is a `kubectl`-error. If I find the time I'll try to add container selection, too.
Fixes #66.

Add --container option to kubernetes-logs-popup

---

kubernetes-commands.el
kubernetes-logs.el

Fix for #73 #64 . Added all the flags to the end of the logs command which fixes the --kubeconfig missing problem.

Adding the all the flags to the command which adds the --kubeconfig if present

---

kubernetes.el

magit switched to using transient[1] for providing popups. As a result,
magit-popup will no longer be installed as a dependency of magit and
must be explicitly required.
[1] https://github.com/magit/transient

Add explicit dependency on magit-popup

---

kubernetes-kubectl.el
test/kubernetes-kubectl-test.el

--show-all is no longer a valid argument
See: kubernetes/kubernetes#69255

Fix call to "kubectl get pods"

---

kubernetes-overview.el
kubernetes-vars.el

I often do not have access to list all namespaces in a k8s context.
I've implemented a new `kubernetes-default-overview-namespace` variable to select a namespace when `kubernetes-overview` is called.
More than happy to make any changes! :smile_cat:

Implement setting for namespace on running kubernetes-overview

---

kubernetes-commands.el

I noticed that the namespace is reset to `default` on switching context.
If the default namespace has been customized, it should be used instead.
Related to #104.
More than happy to make any changes!

Set namespace on switching context

---

kubernetes-kubectl.el
kubernetes-vars.el
test/kubernetes-kubectl-test.el

The existing `kubernetes-kubectl-await-on-async` is not quite general
enough, and hangs forever on an error.
New `kubernetes-kubectl-await` is generalized so that it takes an
arbitrary command and callbacks set (instead of props, state, and an
on-success callback).  It will also give up after
`kubernetes-kubectl-timeout-seconds`.

More flexible kubernetes-kubectl-await

---

kubernetes-kubectl.el
test/kubernetes-kubectl-test.el

Only printing the last error if last-error isn't set suggests no errors would ever be printed.

surface errors

---

kubernetes-modes.el

The redisplay function customizations in `kubernetes-mode` use magit's
`magit-{un,}highlight-region` functions, which were recently renamed
in magit/magit@e4b6497.
Instead of updating `kubernetes-mode` to use the new function names,
let's remove the redisplay function customizations altogether: magit's
functions seem to only handle edge cases of sections with diff hunks
in them, which are not used in this package.
See https://github.com/chrisbarrett/kubernetes-el/issues/116

Remove redisplay function customizations from `kubernetes-mode`

---

kubernetes-pods.el
test/kubernetes-pods-test.el
test/resources/get-pods-response.json

Handles the containers that did not launch, previously if the container did not have a status the pod screen would not render because it failed on looking up non existent keys, now checks and provides defaults when containerrStatuses is missing in the response json.
I struggled with this quite a bit, not much info on dash.el other than the official docs which I struggled with so there may be better ways.
fixes #113

Fix pod display failures when containerStatus is missing in the

---

kubernetes-configmaps.el
kubernetes-contexts.el
kubernetes-deployments.el
kubernetes-ingress.el
kubernetes-jobs.el
kubernetes-kubectl.el
kubernetes-namespaces.el
kubernetes-nodes.el
kubernetes-pods.el
kubernetes-secrets.el
kubernetes-services.el
kubernetes-state.el
kubernetes-statefulsets.el
kubernetes-utils.el
test/kubernetes-kubectl-test.el
test/kubernetes-state-test.el
test/test-helper.el

Calling `kubernetes-pods-refresh` and querying `kubernetes-state-pods` does not guarantee seeing refreshed pods.
Preserved the old behavior of `kubernetes-*resource*-refresh`, and added `kubernetes-*resource*-refresh-now` that is synchronous, i.e., guarantees state is updated.

Synchronous `kubernetes-*resource*-refresh-now`

---

.travis.yml
Cask
kubernetes-loading-container.el

Converts Travis CI to Nix.
Needs `kubectl` installed with Nix to fix a test: https://travis-ci.com/github/peterbecich/kubernetes-el/jobs/376627133#L6520

Travis CI coverage for Emacs 27

---

kubernetes-pods.el
test/kubernetes-pods-test.el
test/resources/get-pods-response.json

Closes #133.
Currently the `pod-view-detail` AST component is implemented to only show the
name and image of the first container that appears in `containerStatuses`. This
results in misleading display of pod details for pods running multiple
containers, as only one container's name and image are displayed:
```
POD_NAME                  Running      2/2          0    10d
Name:       CONTAINER_0_NAME
Namespace:  kubeflow
Image:      CONTAINER_0_IMAGE
Host IP:    10.202.56.91
Pod IP:     10.202.78.194
Started:    2021-04-29T12:26:05Z
```
This PR updates the `pod-view-detail` AST component to display all containers
for a given pod in enumerated list form, like so:
```
POD_NAME                  Running      2/2          0    10d
Namespace:  kubeflow
Host IP:    10.202.56.91
Pod IP: …
```

Pods: Display all containers

---

kubernetes-commands.el

kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.

Update kubectl exec command

---

kubernetes-ast.el
kubernetes-yaml.el
test/kubernetes-ast-test.el
test/kubernetes-yaml-test.el

Closes #81.
Current AST rendering logic for bullet lists was such that lists that
we expect to be rendered like so:
```yaml
args:
- --foo
- --bar
- --baz
```
Were instead getting rendered along the lines of the following:
```yaml
args:
--foo--bar--baz
```
This PR fixes rendering of bullet lists to align with the former
output.
Incidentally, we also fix up a related bug in list rendering that
results in the following expected output:
```yaml
- foo
- -bar
- --baz
```
Instead getting rendered like so:
```yaml
- foo
-bar
--baz
```
Both of these scenarios can be confirmed by checking out the
contributed test cases, less the changes to
`kubernetes-{ast,yaml}.el`, and running them on `master`.

AST: Properly render lists w/ dash-prefixed elements

---

kubernetes-pods.el

CI is failing currently due to the following:
```
kubernetes-pods.el:22:1:Error: variable `_containers' not left unused
```
[Elisp
documentation](https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Using-Lexical-Binding)
points out that underscores should be used only for variables known
not to be used, so we rename the variable used here.

Rename variable to satisfy byte compiler

---

Readme.md

Follows up #146 in moving away from Travis CI.

Update README CI badge for GitHub Actions

---

.github/workflows/ci.yaml

The move towards GitHub Actions for CI in #146 removed code coverage
tracking via Coveralls, which until now had come "for free" via
Travis.
This PR reintroduces Coveralls tracking via the guidance in
[undercover](https://github.com/undercover-el/undercover.el)
documentation. Unfortunately, this only enables tracking, but does not
provide feedback in PR of changes to test coverage like before. Were
undercover to integrate LCOV reporting support (see
undercover-el/undercover.el#68), this could then move to using [the
official Coveralls GitHub
Action](https://github.com/marketplace/actions/coveralls-github-action),
which would give that reporting.

Migrate code coverage tracking to GitHub Actions

---

kubernetes-commands.el
kubernetes-modes.el
test/kubernetes-commands-test.el

Closes #142.
This PR provides a command, `kubernetes-kill-buffers`, that kills every `kubernetes` buffer, doing so by selecting all buffers whose major mode derives from `kubernetes-mode`. It also provides a rudimentary unit test for the new behavior.
This function is inspired largely by [`helpful-kill-buffers`](https://github.com/Wilfred/helpful/blob/master/helpful.el#L2845) from the [`helpful` package](https://github.com/Wilfred/helpful). This implementation expands on the inspiration with both pre- and post-kill confirmation.

Add command to kill all k8s buffers at once

---

.github/workflows/ci.yaml
Cask
test/test-helper.el

Now that `undercover` is compatible with the official [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action) (see undercover-el/undercover.el#68), this PR updates CI to use the official Action for in-PR coverage change reporting etc.

CI: Report coverage using Coveralls GitHub Action

---

kubernetes-pod-line.el
test/kubernetes-pod-line-test.el

The top-level `-let` specification in `kubernetes-pod-line-ok-p` does
not conform to `-let`'s edebug spec, which reads as follows:
```emacs-lisp
[&or (&rest [&or (sexp form) sexp]) (vector [&rest [sexp form]])]
```
Specifically, `line-ok-p` repeats `pod` to provide a length-3 vector rather
than the expected length-2 vector.
This causes `undercover` to fail to parse `kubernetes-pod-line.el` for
coverage, with the following error:
```
UNDERCOVER: Error while loading /Users/jjin/dev/kubernetes-el/kubernetes-pod-line.el for coverage:
UNDERCOVER: Invalid read syntax: "Expected one of", (&rest [&or (sexp form) sexp]), (vector [&rest [sexp form]])
UNDERCOVER: The problem may be due to edebug failing to parse the file.
UNDERCOVER: You can try to narrow down the problem using the following steps: …
```

k8s-pod-line: ok-p: Conform to -let edebug spec

---

kubernetes-state.el

`undercover` fails to parse this particular line with the following
message:
```
UNDERCOVER: Error while loading /Users/jjin/dev/kubernetes-el/kubernetes-state.el for coverage:
UNDERCOVER: Invalid read syntax: "."
UNDERCOVER: The problem may be due to edebug failing to parse the file.
UNDERCOVER: You can try to narrow down the problem using the following steps:
UNDERCOVER: 1. Open "/Users/jjin/dev/kubernetes-el/kubernetes-state.el" in an Emacs buffer;
UNDERCOVER: 2. Run M-: ‘(require 'edebug)’;
UNDERCOVER: 3. Run M-x ‘edebug-all-defs’;
UNDERCOVER: 4. Run M-x ‘toggle-debug-on-error’.
UNDERCOVER: 5. Run M-x ‘eval-buffer’;
UNDERCOVER: 6. In the *Backtrace* buffer, find a numeric position,
UNDERCOVER:    then M-x ‘goto-char’ to it.
```
We can reproduce this w/ `edebug-defun` on the …

k8s-state: update-last-error: Fix non-fatal syntax error

---

Cask

It's unclear to me why the `undo-tree` dependency was introduced in #127 -- nor does it seem used anywhere in the codebase -- so we remove it here.
@noorul + other contributors: let me know if I'm mistaken and the dependency is actually necessary.

Deps: Remove undo-tree

---

kubernetes-overview.el

Today overview is an aggregated view comprising of `statefulsets` and
`deployments`. Handled this special case in
`kubernetes-overview--poll` function.
Suggested by: @egh

Fixed issue #131

---

kubernetes-configmaps.el
kubernetes-deployments.el
kubernetes-ingress.el
kubernetes-jobs.el
kubernetes-nodes.el
kubernetes-pods.el
kubernetes-secrets.el
kubernetes-services.el
kubernetes-statefulsets.el
kubernetes-utils.el
test/kubernetes-services-test.el

`kubernetes-utils-ellipsize` function was using a special character
which was causing formatting issues. Replaced special character with
ASCII `...`.
Above change was not alone enough. Passed correct threshold value to
`kubernetes-utils-ellipsize`.

Modified format lines to have consistent view

---

kubernetes-logs.el

`M-w` is bound to `kubernetes-copy-thing-at-point` in kubernetes major
mode. Since there is no specific behavior for this key in log buffer
it is better to fall back to global binding for the same.

Fixed #161: Unbind `M-w` in kubernetes-logs-mode

---

kubernetes-pods.el
kubernetes-vars.el
test/kubernetes-kubectl-test.el
test/kubernetes-pods-test.el
test/resources/get-pods-response.json

Today we are filtering out pods with Succeeded phase in the pods' list
view. Introduced a new custom variable to configure this behavior. If
the value of the variable is non-nil, then display all the pods.
Fixes #166

Added new custom variable `kubernetes-pods-display-completed`

---

kubernetes-evil.el
kubernetes-modes.el
kubernetes-popups.el
kubernetes-tramp.el
kubernetes.el

Add some basic tramp support.
Includes a new popup menu for files (`f`).
I abused the `user` parameter for tramp to support different containers for the same pod. This doesn't feel great, but since `user` is not a valid option for `kubectl exec` it shouldn't be a huge problem.
I'm unhappy with the container prompt logic. It is an option to the file commands, but magit-popup doesn't seem to support required parameters, and it would be very strange to open a file in a container without knowing which container in the pod was being used, it seems necessary to prompt the user for a container explicitly. But this feels strange with the magit-popup option as well.
I named the tramp method `kubernetes` to avoid a clash with the https://github.com/gruggiero/kubernetes-tramp project.
Screenshot of …

Basic tramp support

---

kubernetes-commands.el
kubernetes-configmaps.el
kubernetes-contexts.el
kubernetes-deployments.el
kubernetes-ingress.el
kubernetes-jobs.el
kubernetes-loading-container.el
kubernetes-nodes.el
kubernetes-pod-line.el
kubernetes-pods.el
kubernetes-secrets.el
kubernetes-services.el
kubernetes-statefulsets.el
kubernetes-utils.el
kubernetes-vars.el
test/kubernetes-configmaps-test.el
test/kubernetes-contexts-test.el
test/kubernetes-deployments-test.el
test/kubernetes-ingress-test.el
test/kubernetes-jobs-test.el
test/kubernetes-nodes-test.el
test/kubernetes-pods-test.el
test/kubernetes-secrets-test.el
test/kubernetes-services-test.el
test/kubernetes-statefulsets-test.el

Partially addresses #2.
This PR replaces all use of the Magit face `magit-dimmed` with
`kubernetes-dimmed`, a carbon copy thereof.

Faces: Replace magit-dimmed with kubernetes-dimmed

---

kubernetes-ast.el
kubernetes-loading-container.el
test/kubernetes-configmaps-test.el
test/kubernetes-deployments-test.el
test/kubernetes-ingress-test.el
test/kubernetes-nodes-test.el
test/kubernetes-pods-test.el
test/kubernetes-secrets-test.el
test/kubernetes-services-test.el
test/kubernetes-statefulsets-test.el

Partially addresses #2.
This PR replaces all use of the `magit-header-line` face with
`magit-section-heading`, which the former directly inherits from
without modification (see [definition in
`magit/magit/lisp/magit.el`](https://github.com/magit/magit/blob/master/lisp/magit.el#L71-L77)).
This change will help us slowly obviate our dependency on `magit`
itself in favor of `magit-section` and `transient`.

Faces: Replace magit-header-line w/ magit-section-heading

---

kubernetes-ast.el
kubernetes-ingress.el
kubernetes-modes.el
kubernetes-vars.el

Partially addresses #2.
This PR replaces the `magit-branch-remote` and `magit-tag` parent
faces with their literal counterparts. I believe this is the last of
the faces inherited from Magit proper.
Incidentally, this PR also replaces some `require`s of `magit` in
packages that only use `magit-section` constructs with
`magit-section`, helping to further remove dependency on Magit proper.

Remove more traces of core Magit package

---

.github/workflows/ci.yaml
test/test-helper.el

Coveralls reports don't seem to display the source code when using the
official Github Action, with no obvious documented solution.
Meanwhile, Codecov seems to work just fine, with the added benefits
of: more streamlined CI configuration; and more elegant and insightful
reporting. See, for example, the report generated from [this particular commit](https://codecov.io/gh/kubernetes-el/kubernetes-el/tree/0b4f4bc2257b94fdc6a0ccd19c702df9e93372a8), which doesn't show coverage comparison reporting between `master` and the PR branch (due to Codecov not having been run on `master` yet) but gives the general idea.
We propose switching to Codecov here. @noorul, if you approve, we can
update README badge after merge.

CI: Switch test coverage to Coveralls

---

kubernetes.el

Closes #151.
Now that all Magit-inherited faces have been replaced by faces we
define within the package itself (see #2), we can safely eliminate the
dependency on Magit itself.
We do so here, swapping out `magit` for the tighter-scoped
`magit-section`, which additionally is actually designed for
consumption as a package dependency.

Deps: Remove magit in favor of magit-section

---

Readme.md
kubernetes-commands.el
kubernetes-kubectl.el
kubernetes-modes.el
kubernetes-popups.el
kubernetes.el
test/kubernetes-kubectl-test.el

* Added new pop-up key E, as e is unavailable.
* Used with-editor package as the driver for this functionality.
* Added tests
Why is this fix partial?
* I am exploring a way to provide custom key bindings to the edit
buffer like the Magit commit buffer. But I am not successful yet.

Added edit resource functionality (Partial fix for #124)

---

kubernetes-utils.el
test/kubernetes-utils-test.el

This PR hardens the following functions against invocation in unexpected
contexts, e.g. when `kubernetes-state` is `nil` or when the overview buffer
isn't available:
- `kubernetes-utils-read-container-name`
- `kubernetes-utils-maybe-pod-name-at-point`
We also contribute unit tests accordingly.

Make some util functions resilient to unexpected calling contexts

---

kubernetes-utils.el
test/kubernetes-utils-test.el

Additionally, we document and test for the expected behavior on invalid input,
e.g. empty a-list.

Add unit tests for `kubernetes-get-pod-container-names`

---

kubernetes-commands.el
kubernetes-configmaps.el
kubernetes-deployments.el
kubernetes-ingress.el
kubernetes-jobs.el
kubernetes-kubectl.el
kubernetes-namespaces.el
kubernetes-nodes.el
kubernetes-pods.el
kubernetes-secrets.el
kubernetes-services.el
kubernetes-state.el
kubernetes-statefulsets.el
test/kubernetes-kubectl-test.el

Relates to #69.
Currently, we define one function for `get`ting all entities of a given resource type, for each of a finite set of resources, e.g. `k8s-kubectl-get-{pods, nodes, ...}`. All of these functions are identical save for the resource type that they retrieve.
As such, we generalize to a single implementation—`k8s-kubectl-get`—that accepts the resource type name and performs the `get` accordingly.
By extension, we rewire all call sites that assume the existence of per-type `get` functions to use the genericized counterpart—most notably the `kubernetes-state-define-refreshers` macro, which currently literally expects functions of those naming pattern to exist.
Similarly, we consolidate unit tests and, finally, remove the granular, per-type `get` functions.

Genericize `kubectl get` operations

---

kubernetes-commands.el
kubernetes-configmaps.el
kubernetes-ingress.el
kubernetes-overview.el
kubernetes-state.el
test/kubernetes-state-test.el

This PR removes the ConfigMap-specific getters for marked ConfigMaps and ConfigMaps pending deletion. In doing so, we also update all callsites to use the resource-generic `kubernetes-state--get` function.

Replace resource-specific getters for marked/pending-deletion ConfigMaps w/ genericized counterpart

---

kubernetes-commands.el
kubernetes-configmaps.el
kubernetes-deployments.el
kubernetes-errors.el
kubernetes-ingress.el
kubernetes-jobs.el
kubernetes-overview.el
kubernetes-pod-line.el
kubernetes-pods.el
kubernetes-props.el
kubernetes-secrets.el
kubernetes-services.el
kubernetes-state.el
kubernetes-statefulsets.el
test/kubernetes-state-test.el

Relates to #69.
This PR removes the resource-specific getters for "marked" default k8s resources, e.g. pods and deployments, in favor of the generic counterpart introduced in #200.
As we move forward with resource-handling genericization, it might benefit us to likewise look into a more generic handling of marked status for resources, rather than introduce one new field in the state alist for each resource. We can have that discussion elsewhere.

Genericize state-getters for marked resources

---

kubernetes-commands.el
kubernetes-configmaps.el
kubernetes-contexts.el
kubernetes-deployments.el
kubernetes-el-tramp.el
kubernetes-ingress.el
kubernetes-jobs.el
kubernetes-kubectl.el
kubernetes-labels.el
kubernetes-logs.el
kubernetes-namespaces.el
kubernetes-nodes.el
kubernetes-overview.el
kubernetes-pods.el
kubernetes-secrets.el
kubernetes-services.el
kubernetes-state.el
kubernetes-statefulsets.el
test/kubernetes-pod-line-test.el
test/kubernetes-state-test.el

Relates to #69.
This PR removes the resource-specific getters for default k8s resources, e.g. pods and deployments, in favor of the generic counterpart introduced in #200.

Genericize state-getters for default k8s resources

---

CHANGELOG.org

This PR proposes the introduction of a changelog practice to the project.
Changelogs are a helpful way for users to be made aware of changes to the
package from version to version. It does not replace GitHub's
[releases](https://github.com/kubernetes-el/kubernetes-el/releases) page for the
project, but rather supplements it. Package maintainers can add entries to the
changelog's "Unreleased" section as we implement changes, copying over the
contents into a new version's section and notes when we cut a new version.
Details of this process are explained further in
[keepachangelog.com](https://keepachangelog.com/en/1.0.0/). We base this
changelog on the aforementioned methodology.

Start a changelog

---

contributing.org

We recently adopted the changelog procedure outlined at
keepachangelog.com. However, we make no mention of it in the contributor guide,
leading to unnecessary back-and-forth and explanation between maintainers and
contributors.
To avoid confusion and provide clarity moving forward, we note the procedure in
the contributor guide here.

Docs: Contributing: Mention changelog procedure

---

kubernetes-commands.el

Updates function call for `kubernetes-execute-marks` when deleting deployments to also use `kubernetes-state--get state`.

Fix deleting marked deployments

---

kubernetes-state.el

Relates to #69.
This PR extracts the core of the resource-specific
`kubernetes-<resource>-refresh-now` functions into the resource-generic
`kubernetes-state--refresh-now` function. This function represents the "core" of
the function template used to generate the resource-specific force-refresh
functions.
This PR leaves the resource-specific refresh-now functions in place,
re-implementing them as wrappers around the new resource-generic version. The
resource-specific functions have test coverage, which provides a vote of
confidence as to the safety of this change. We'll leave sunsetting of the
resource-specific functions' use to subsequent PRs.

Extract generic form of resource force-refresh logic

---

kubernetes-kubectl.el

This PR updates `kubernetes-kubectl` to invoke the underlying process with
stdout/stderr buffers named after the invocation in question. This will allow
multiple concurrent invocations thereof, each with their own output buffers.
This will facilitate #122.

kubernetes-kubectl: Enable multiple simultaneous invocations

---

kubernetes-process.el
test/kubernetes-kubectl-test.el
tests/test-process.el

Relates to #234.
As the first step towards a resource-agnostic process tracking strategy, this PR
implements `kubernetes--process-ledger`, an EIEIO-based ledger class to keep
track of processes corresponding to given resources. This PR also reimplements
the existing resource-specific process-related constructs,
e.g. `kubernetes-process-pods-process-live-p`, to be with respect to a global
instance of this new ledger class.

Process tracking: Implement new, comprehensive, agnostic tracker

---

kubernetes-process.el
tests/test-process.el

Relates to #234.
This PR consolidates the hard-coded per-resource logic in
`kubernetes-process-kill-polling-processes` into a method on the general-purpose
process ledger introduced in #237 called, appropriately, `release-all`.
In doing so, we redefine `kubernetes-process-kill-polling-processes` to simply
be a wrapper around said method.

kubernetes-process: Implement release-all method for ledger

---

CHANGELOG.org
kubernetes-process.el
kubernetes-state.el

Closes #234.
This PR caps off the groundwork laid by #237 and #238, rendering process
tracking fully resource-agnostic.

Use global process ledger everywhere directly

---

CHANGELOG.org
kubernetes-evil.el

Relates to #124.
Added missing Evil keybinding for `kubernetes-edit`. Otherwise E goes to the end of word.

Evil: Add kubernetes-edit action

---

.github/workflows/ci.yaml

Given that Python 3.6 has reached EoL.

CI: Bump Python version from 3.6 to 3.9

---

kubernetes-commands.el
kubernetes-core.el
kubernetes-vars.el

This PR introduces rudimentary mechanisms for leveled logging, e.g. `INFO`,
`WARNING`, and `ERROR`, as well as a custom variable with which users can
disable such logs. It's copied basically wholesale from [lsp-mode's
implementation][1].
[1]: https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el

Introduce rudimentary leveled-logging constructs

---

kubernetes-process.el
kubernetes.el
tests/test-process.el

Contributes to #247.
This PR introduces `kubernetes--ported-process-record`, a class that facilitates
interaction with processes that correspond to local ports. It provides methods
such as:
- Interpolating the base URL, e.g. `http://localhost:<port>`;
- Waiting for response code from a specific endpoint thereon,
e.g. `http://localhost:<port>/livez` (for the Kubernetes server);
This class will be necessary for systematic tracking of proxy servers created by
`kubectl` as outlined in #247 and implemented in #252.

Introduce primitives for tracking processes w/ ports + addresses

---

.github/codecov.yml

This commit configures Codecov to issue an informational, i.e. non-blocking,
nudge on PRs and commits that contribute to a decrease in test coverage above a
certain quantity. See [Codecov documentation][1] for details.
[1]: https://docs.codecov.com/docs/commit-status

CI: Notify when PR drops test coverage by certain amount

---

Makefile
docs/CHANGELOG.md
kubernetes-commands.el
kubernetes-kubectl.el
test/kubernetes-kubectl-test.el

Kubernetes tramp was not respecting set namespace as there are
limitations to what we can pass to `tramp-login-args`. The fix adds
one more step to update the `kubectl` configuration.

fix: Persist namespace change to `kubectl` configuration (#264)

---

docs/contributing.md
mkdocs.yaml

Add `strict: true` to cause failures during documentation build time to be
fatal.

Docs: enable strict mode

---

docs/CHANGELOG.md
docs/contributing/index.md
docs/getting-started/index.md
docs/index.md
docs/references/compatibility.md
docs/references/index.md
mkdocs.yaml

This PR makes the following documentation refinements:
- Move version compatibility information to a new References section;
- Take advantage of richer formatting for installation instructions;
- Call out the documentation's adherance to the [Diataxis] framework.
[Diataxis]: https://diataxis.fr/

Docs: Refine and reorganize

---

Readme.md

This uses star-history.com's API to inject a chart plotting kubernetes-el's GitHub star growth over its lifespan. See [here](https://star-history.com/#kubernetes-el/kubernetes-el).

README: Add chart plotting repo star growth

---

.github/workflows/ci.yaml
.pre-commit-config.yaml
docs/index.md

We also remove redundant minor versions of back versions, e.g. `26.1`.

CI: Test against Emacs 28.x

---

kubernetes-commands.el
kubernetes-configmaps.el
kubernetes-deployments.el
kubernetes-ingress.el
kubernetes-jobs.el
kubernetes-nodes.el
kubernetes-persistentvolumeclaims.el
kubernetes-pod-line.el
kubernetes-pods.el
kubernetes-secrets.el
kubernetes-services.el
kubernetes-statefulsets.el
kubernetes-utils.el
test/kubernetes-configmaps-test.el
test/kubernetes-ingress-test.el

The `kubernetes-utils-ellipsize` is **basically** made redundant by
`s-truncate`, so for simplicity's sake we use that instead.
This results in a slight functionality change. Namely, the former
appends `//` for multi-line string inputs, whereas the latter does
not. Preserving this behavior does not seem particularly valuable, so we
opt not to do so here.

Remove custom string truncate function; use `s-truncate`

---

.gitignore
Brewfile
docs/contributing/index.md

As of now, package development has at minimum the following non-Emacs dependencies:
- Cask;
- Graphviz, for `dot`;
- Pre-commit.
As a potential contributor, it is unwieldy and cumbersome to have to discover
these either just-in-time or from a list in the contributors' guide that can
easily go stale.
This PR provides a Brewfile enumerating these dependencies such that new
contributors can onboard simply with:
```bash
$ brew bundle
```

Add Brewfile for development dependencies

---

.all-contributorsrc
.gitattributes
.pre-commit-config.yaml
docs/CONTRIBUTORS.md
docs/contributing/index.md
docs/index.md
mkdocs.yaml

This PR implements the [all-contributors spec](https://allcontributors.org) to
visibly acknowledge and celebrate all past contributors and their work. It
will be accompanied by installation of the corresponding
[bot](https://allcontributors.org/docs/en/bot/overview) to allow us to update
the contributors table directly from within PRs and the like.

Implement all-contributors spec

---

docs/CHANGELOG.md
kubernetes-core.el

Fixes #295.
Moves `kubernetes--save-window-state` to the top of the file to ensure it's compiled in time.

Move `kubernetes--save-window-state` macro to top of the file

---

kubernetes-process.el
kubernetes-resources.el
tests/test-resources.el

Contributes to #235.
This PR adds the `kubernetes--get-all-groups` function. This queries the Kubernetes
API via HTTP proxy to discover the API groups present on the cluster.
At the same time, we also introduce a collection of macros to facilitate
interaction with `kubectl` proxy servers, e.g. lifecycle management.
This logic represents the first step to discovering all resource kinds, custom
or otherwise, on the given cluster.

Enable discovery of API groups from cluster

---

docs/CHANGELOG.md
kubernetes-commands.el

The namespace-change callback messages as currently implemented display the current namespace rather than the post-change namespace.

Fix message on switching namespace to properly show new namespace

---

kubernetes-state.el

This PR removes two macros that exist solely for generating boilerplate functions. They are unnecessarily complex and severely hinder the flexibility of this codebase.

Excise define-getter and define-accessors macros

---

kubernetes-commands.el
kubernetes-utils.el
test/kubernetes-utils-test.el

Add generic resource information extraction utilities to kubernetes-utils.el
that centralize the logic for getting resource type and name at point. Refactor
kubernetes-edit-command to use these utilities instead of repetitive pcase
expressions for each resource type.

refactor: simplify resource editing with generic utility function

---

kubernetes-logs.el
kubernetes-utils.el
test/kubernetes-logs-test.el
test/kubernetes-utils-test.el

Add support for viewing logs from deployments, statefulsets, and jobs
in addition to pods. This improves workflow by allowing users to view
logs directly from higher-level resources without manually selecting
pods.

feat(logs): support additional resource types for logs command

---

kubernetes-logs.el

Add two new flag options in kubernetes-logs command interface:
- `-A` flag to fetch logs from all pods
- `-P` flag to prefix each log line with pod name and container name
These additions enhance the log viewing capabilities by allowing users
to view logs across multiple pods simultaneously with clear

feat: add options to get logs from all pods with prefixed output

---

kubernetes-exec.el
test/kubernetes-exec-test.el

This change renames the function to better reflect its actual purpose:
switching between Kubernetes exec buffers rather than just listing them.
The keybinding for this function has also been updated from "l" to "b".

refactor: rename kubernetes-exec-list-buffers to kubernetes-exec-switch-buffers

---

kubernetes-exec.el
kubernetes-logs.el
test/kubernetes-exec-test.el
test/kubernetes-logs-test.el

Standardize resource path formatting in both kubernetes-exec.el and kubernetes-logs.el
to consistently use the "resource-type/resource-name" format for all resource types
instead of having special handling for "pod" resources.

fix(kubectl): use consistent resource path format across kubectl interactions

---

kubernetes-exec.el
kubernetes-logs.el
kubernetes-utils.el
test/kubernetes-utils-test.el

This refactors duplicated container name extraction logic by creating a
`kubernetes-utils--extract-container-name-from-args` utility function.
The function extracts container names from command line arguments and
is now used consistently in both kubernetes-exec.el and kubernetes-logs.el.

refactor: extract container name logic into dedicated utility function

---

.dir-locals.el

Configures projectile command settings to use "make" for compilation
and "make test" for testing within the Emacs environment.

build: add .dir-locals.el for Emacs project settings

---

kubernetes-overview.el
kubernetes-pod-line.el
test/kubernetes-overview-test.el

Refactor resource overview component to simplify display by:
- Remove selector, component, and match expressions display
- Improve pod state extraction with safer container state handling
- Simplify aggregated-pods component to work with any resource type
- Remove unused aggregated-deployment-detail component
Fixes #360

refactor: simplify pod display in overview and improve pod state handling

---

kubernetes-pods.el
test/kubernetes-pods-test.el
test/resources/get-pods-response.json

This change enhances the pod display to show init containers in the UI.
It shows init containers either from status or falls back to spec info
if not available in status. Also adds support for showing container
details from spec when status information is not available.
Fixes #362

feat(pods): add support for init containers display

---

kubernetes-exec.el
kubernetes-logs.el
kubernetes-popups.el
kubernetes-utils.el
test/kubernetes-exec-test.el
test/kubernetes-logs-test.el
test/kubernetes-utils-test.el

Refactor resource selection logic in `kubernetes-exec` and
`kubernetes-logs` modules to prioritize manually selected resources
over resources at point. Updated corresponding test cases to reflect
the new behavior.

feat(exec, logs): prioritize manually selected resources over point-based resources
